### ISSUE TITLE
pre-commit hooks and language

### ISSUE THREAD

**Issue by alefteris** [rvben/rumdl#7]
Some comments/suggestions about the pre-commit integration:

1. It seems that both hooks have `entry: rumdl`. If I understand correctly, they will do the same thing, check only.
2. I think a single hook could also be enough and a hook user can configure fixing like this:
    ```yaml
  - repo: https://github.com/rvben/rumdl
    rev: v0.0.42
    hooks:
      - id: rumdl
        args:
          - --fix
    ```
4. Since the project already provides a Python package (I think it's an advantage compared to other tools) and pre-commit already requires Python installed, it would be better if the hook language was set to Python. This would avoid the need for pre-commit to install the Rust toolchain to install rumdl. It would make the hook first installation faster and easier for Windows environments I guess (that's the major reason I'm looking for an alternative to markdownlint as it requires Node.js installed in addition to Python for pre-commit). But it might require having a separate repo for it, looking at how they do it for ruff at [astral-sh/ruff-pre-commit](https://github.com/astral-sh/ruff-pre-commit/)
